### ISSUE TITLE
Sample program UploadSingleWaypointRoute fails with Route Processing Error

### ISSUE THREAD

**Issue by HillCharles** [ugcs/ugcs-java-sdk#12]
Good day,
I am running version ugcs-java-sdk version 3.6 on Windows 10 with UGCS-3.6.248. I am able to successfully run the ListenTelemetry and SendCommand samples.

When I run the UploadSingleWaypointRoute the following message is displayed on the console:
  MS_ERROR: There is no parameter named "altitudeType".
  java.lang.IllegalStateException: Route processing error
	at com.ugcs.ucs.client.ClientSession.processRoute(ClientSession.java:151)
	at com.ugcs.ucs.client.samples.UploadSingleWaypointRoute.uploadSingleWaypointRoute(UploadSingleWaypointRoute.java:131)
	at com.ugcs.ucs.client.samples.UploadSingleWaypointRoute.main(UploadSingleWaypointRoute.java:79)

Can you please let me know why this is happening, and what I can do to resolve the issue.

Many thanks

**Comment by C4ET4uK** [comment]
Hi! Looks like this sample is a bit outdated. For example in 3.6 we add parameter altitudeType to some algorithms. And also uploading of not saved route is now prohibited. We will update this sample to make it works.

**Comment by C4ET4uK** [comment]
Hi! Today we released a new version of SDK. There you can find updated samples.
