### ISSUE TITLE
Adding wait action to Route Segment

### ISSUE THREAD

**Issue by HillCharles** [ugcs/ugcs-java-sdk#14]
I can see that the SegmentDefinition.newBuilder() supports addActionDefinitions but I a struggling to create a DomainProto.WaitDefinition. Can you possibly help?

I want the drone to wait for 10 seconds at the waypoint.

            DomainProto.WaitDefinition wd=??? how to create wd ???
            
            SegmentDefinition.Builder routeSegment = SegmentDefinition
                    .newBuilder()
                    .setAlgorithmClassName("com.ugcs.ucs.service.routing.impl.WaypointAlgorithm")
                    .setFigure(figure)
                    .addActionDefinitions(DomainProto.ActionDefinition.newBuilder()
                            .setWaitDefinition(wd))

Many thanks

**Comment by C4ET4uK** [comment]
Hi! It's more about protobuff syntax. 

> 		DomainProto.WaitDefinition wd= DomainProto.WaitDefinition.newBuilder()
> 				.setInterval()
> 				.build();
