### ISSUE TITLE
Cant get parameters from vehicle (want to get lowBatteryVoltage and dischargedBatteryVoltage)

### ISSUE THREAD

**Issue by HillCharles** [ugcs/ugcs-java-sdk#15]
I am trying to read  lowBatteryVoltage and dischargedBatteryVoltage of the selected Vehicle (EMU-101). My code is:
                        DomainProto.Vehicle vehicle = session.lookupVehicle(name);
                        VehicleProfile vp = vehicle.getProfile();
                        List<DomainProto.VehicleParameter> lvp = vp.getParametersList();

If I look at vp in the debugger I do not see any fields that could contain lowBatteryVoltage and dischargedBatteryVoltage. Also lvp contains an empty list.

When would these fields be filled in?

**Comment by C4ET4uK** [comment]
Hi! lookupVehicle method return vehicle without dependencies (parameters in this case). So you can use a more generic method getObjectListRequest, or getObjectRequest, with property refreshDependency=true
