### ISSUE TITLE
tlm to csv

### ISSUE THREAD

**Issue by MorPal** [ugcs/ugcs-java-sdk#4]
Hi, i am new with this program, how can i use it in ubuntu for convert a tlm file to csv?

**Comment by episarenko** [comment]
Hi,

First of all download the distfile and unpack it somewhere: https://github.com/ugcs/ugcs-java-sdk/releases/download/2.10/ugcs-telemetry-tool-2.10.zip. Make sure you have java installed and added to the environment path.

Then follow these instructions: https://github.com/ugcs/ugcs-java-sdk/tree/master/ucs-telemetry-tool.
The most common case is to run

$ tlm2csv -t 60 -f your_telemetry_file.tlm -d .

which will add converted .csv files into the current directory.

**Comment by MorPal** [comment]
Hi, now it works, only one thing,  in this line, i have to add "csv" at the end, like this:

 $ tlm2csv -t 60 -f your_telemetry_file.tlm -d csv

that way it works perfect

Thanks you!!

Edit: ok, now is working also when it finish with the "point". I don´t know why wasn´t working before. But now it works with both lines.

**Comment by Dumojon88** [comment]
Hi, I'm very much a nube at this. Trying to convert TLM to CSV using the command line prompt and instructions provided by UgCS and this thread. When I use the " tlm2csv -t 60 -f your_telemetry_file.tlm -d ." command it comes back with "Error: Could not find or load main class Files"
I have tried various combinations as well as renaming the tlm file (it is in the telemetry tool 2.11 folder beside the *.bat files... 
Thanks for the help!

**Comment by episarenko** [comment]
Hi, please make sure that you cd to a directory containing tlm2csv script before invoking the script.
It is only relevant for older versions and not required in release 3.0 where you can invoke script from any directory.
