### ISSUE TITLE
Wrong telemetry

### ISSUE THREAD

**Issue by procopionr** [ugcs/ugcs-java-sdk#6]
Hi:

I am trying to read telemetry with version 2.13. But in the latitude and longitude these erroneous values ​​appear:

{"id": "TT_LATITUDE", "value": 0.33958137}, {"id": "TT_LONGITUDE", "value": - 1.7310266}

You have to do some calculation to obtain to get the positions like this: "19.456566, -99.180498.61.17" WGS-84.

Thanks in advance 

Regards

**Comment by episarenko** [comment]
Hi @Stranger87123,

All telemetry angles are measured in radians. To get degrees you need to convert.

**Comment by procopionr** [comment]
Thank you very much for your answer.

I have an other question:

It is possible through Java to manipulate the movements of the camera or drone for DJI Phantom 4

Thanks in advance

Regards

**Comment by episarenko** [comment]
> It is possible through Java to manipulate the movements of the camera or drone for DJI Phantom 4

You can use a direct_payload_control command for that. See http://docs.ugcs.com/ucs_vsm_commands_page.html#c_direct_payload_control
